theme: jekyll-theme-minimal
title: Samuel Lee
logo: /images/sl.png
description: > # your text below (remove <br> elements if you don't need line breaks)
  this is all me
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/samuel-lwl/">LinkedIn</a> | <a href="https://github.com/samuel-lwl">GitHub</a> | <a href="https://drive.google.com/file/d/1VTBeAl2UlZBQkjsO6xO5aQ1YnPkitGFJ/view?usp=sharing">Resume</a>
