theme: jekyll-theme-minimal
title: <center>Hi there, I'm Samuel!</center>
logo: /images/circle-cropped-sl.png
description: > # your text below (remove <br> elements if you don't need line breaks)
  <b><center>DATA PROFESSIONAL</b></center>
  <br>
  I have 5 years of experience in data science, analytics, machine learning, and data engineering, working across diverse environments—from startups in the consumer goods sector to big tech at TikTok. I also hold a <a href="https://www.parchment.com/u/award/64bc9204028d5bf80c1935f8ef169fe2">Master's in Computer Science from Georgia Tech.
  <br><br>
  <center><a href="https://www.linkedin.com/in/samuel-lwl/">LinkedIn</a> | <a href="https://github.com/samuel-lwl">GitHub</a> | <a href="https://drive.google.com/file/d/1W0bqlKyiOX8YWubtIG5nvEzVOWKcuxtR/view?usp=sharing">Resume</a></center>
  <center><a href="mailto: samuel-lwl@outlook.com">Email</a> | <a href="https://leetcode.com/koukishin/">Leetcode</a></center>
